# Generated by Django 4.2.6 on 2023-11-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuento',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='poema',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
